// <auto-generated />
using System;
using CafeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeAPI.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260111113152_InitialCreateDb")]
    partial class InitialCreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Супы"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Салаты"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Закуски"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Основные блюда"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Пицца"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Паста"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Десерты"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Напитки"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Гарниры"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Соусы"
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Available = true,
                            CategoryId = 1,
                            Description = "Классический украинский борщ с мясом, свеклой и сметаной",
                            Name = "Борщ",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Available = true,
                            CategoryId = 1,
                            Description = "Лёгкий куриный бульон с домашней лапшой",
                            Name = "Куриный суп с лапшой",
                            Price = 350m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Available = true,
                            CategoryId = 1,
                            Description = "Нежный суп-пюре из лесных грибов с гренками",
                            Name = "Грибной крем-суп",
                            Price = 420m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Available = true,
                            CategoryId = 2,
                            Description = "Салат с курицей, сыром пармезан и сухариками",
                            Name = "Цезарь с курицей",
                            Price = 480m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Available = true,
                            CategoryId = 2,
                            Description = "Огурцы, помидоры, фета, оливки, красный лук",
                            Name = "Греческий салат",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 6,
                            Available = true,
                            CategoryId = 2,
                            Description = "Микс свежих овощей с оливковым маслом",
                            Name = "Витаминный салат",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 7,
                            Available = true,
                            CategoryId = 3,
                            Description = "Хрустящий хлеб с томатами, базиликом и оливковым маслом",
                            Name = "Брускетта с томатами",
                            Price = 350m
                        },
                        new
                        {
                            MenuItemId = 8,
                            Available = true,
                            CategoryId = 3,
                            Description = "Тонко нарезанная говядина с лимонным соусом",
                            Name = "Карпаччо из говядины",
                            Price = 700m
                        },
                        new
                        {
                            MenuItemId = 9,
                            Available = true,
                            CategoryId = 3,
                            Description = "Сыр моцарелла с томатами и базиликом",
                            Name = "Моцарелла с томатами",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 10,
                            Available = true,
                            CategoryId = 4,
                            Description = "Сочный говяжий стейк, прожарка по желанию",
                            Name = "Стейк рибай",
                            Price = 1500m
                        },
                        new
                        {
                            MenuItemId = 11,
                            Available = true,
                            CategoryId = 4,
                            Description = "Куриное филе на гриле с пряными травами",
                            Name = "Курица гриль",
                            Price = 950m
                        },
                        new
                        {
                            MenuItemId = 12,
                            Available = true,
                            CategoryId = 4,
                            Description = "Мясо свинины с соусом BBQ и овощами",
                            Name = "Свинина в соусе барбекю",
                            Price = 1050m
                        },
                        new
                        {
                            MenuItemId = 13,
                            Available = true,
                            CategoryId = 5,
                            Description = "Томатный соус, сыр моцарелла, базилик",
                            Name = "Маргарита",
                            Price = 650m
                        },
                        new
                        {
                            MenuItemId = 14,
                            Available = true,
                            CategoryId = 5,
                            Description = "Пицца с пепперони и сыром моцарелла",
                            Name = "Пепперони",
                            Price = 750m
                        },
                        new
                        {
                            MenuItemId = 15,
                            Available = true,
                            CategoryId = 5,
                            Description = "Моцарелла, горгонзола, пармезан, чеддер",
                            Name = "Четыре сыра",
                            Price = 850m
                        },
                        new
                        {
                            MenuItemId = 16,
                            Available = true,
                            CategoryId = 6,
                            Description = "Спагетти с мясным соусом и пармезаном",
                            Name = "Спагетти Болоньезе",
                            Price = 700m
                        },
                        new
                        {
                            MenuItemId = 17,
                            Available = true,
                            CategoryId = 6,
                            Description = "Паста с кремовым соусом и сыром",
                            Name = "Феттучини Альфредо",
                            Price = 650m
                        },
                        new
                        {
                            MenuItemId = 18,
                            Available = true,
                            CategoryId = 6,
                            Description = "Паста с креветками, кальмарами и чесночным соусом",
                            Name = "Паста с морепродуктами",
                            Price = 950m
                        },
                        new
                        {
                            MenuItemId = 19,
                            Available = true,
                            CategoryId = 7,
                            Description = "Классический итальянский десерт с маскарпоне и кофе",
                            Name = "Тирамису",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 20,
                            Available = true,
                            CategoryId = 7,
                            Description = "Тёплый шоколадный кекс с жидкой начинкой",
                            Name = "Шоколадный фондан",
                            Price = 420m
                        },
                        new
                        {
                            MenuItemId = 21,
                            Available = true,
                            CategoryId = 7,
                            Description = "Классический чизкейк с клубничным соусом",
                            Name = "Чизкейк Нью-Йорк",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 22,
                            Available = true,
                            CategoryId = 8,
                            Description = "Эспрессо с горячим молоком и пенкой",
                            Name = "Капучино",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 23,
                            Available = true,
                            CategoryId = 8,
                            Description = "Классический черный чай",
                            Name = "Чай черный",
                            Price = 150m
                        },
                        new
                        {
                            MenuItemId = 24,
                            Available = true,
                            CategoryId = 8,
                            Description = "Свежевжатый апельсиновый сок",
                            Name = "Сок апельсиновый",
                            Price = 200m
                        },
                        new
                        {
                            MenuItemId = 25,
                            Available = true,
                            CategoryId = 9,
                            Description = "Хрустящий картофель фри",
                            Name = "Картофель фри",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 26,
                            Available = true,
                            CategoryId = 9,
                            Description = "Отварной рис с овощами",
                            Name = "Рис с овощами",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 27,
                            Available = true,
                            CategoryId = 9,
                            Description = "Сезонные овощи на пару",
                            Name = "Овощи на пару",
                            Price = 230m
                        },
                        new
                        {
                            MenuItemId = 28,
                            Available = true,
                            CategoryId = 10,
                            Description = "Сладко-пряный соус для мяса",
                            Name = "Соус BBQ",
                            Price = 100m
                        },
                        new
                        {
                            MenuItemId = 29,
                            Available = true,
                            CategoryId = 10,
                            Description = "Соус из томатов для пиццы и пасты",
                            Name = "Томатный соус",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 30,
                            Available = true,
                            CategoryId = 10,
                            Description = "Нежный соус со сметаной и зеленью",
                            Name = "Сметанный соус",
                            Price = 80m
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CafeAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CafeAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Waiter"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Cook"
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Admin",
                            Login = "admin",
                            PasswordHash = "$2a$12$.gijsKvNhylDhZfxAknuDesvmZnx13DhA2NVKk9LZH32YiRAQM8YW",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Waiter",
                            Login = "waiter",
                            PasswordHash = "$2a$12$C2Ek4ejvfw.so/k2AezYpuflw5YAaQ4vmHqU0xq0Gmz85Z.I3bSyG",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Cook",
                            Login = "cook",
                            PasswordHash = "$2a$12$9iwlfcfL1S1uYa7BLe3xZO03pZ7mOTQzZDDGWOP7h/Xq4GaCSNBCm",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.HasOne("CafeAPI.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.HasOne("CafeAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeAPI.Models.OrderItem", b =>
                {
                    b.HasOne("CafeAPI.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeAPI.Models.Payment", b =>
                {
                    b.HasOne("CafeAPI.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CafeAPI.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.HasOne("CafeAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafeAPI.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CafeAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
