// <auto-generated />
using System;
using CafeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeAPI.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    partial class CafeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Супы"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Салаты"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Закуски"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Основные блюда"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Пицца"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Паста"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Десерты"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Напитки"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Гарниры"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Соусы"
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.DishItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("DishItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150m,
                            IngredientId = 1,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 2,
                            Amount = 80m,
                            IngredientId = 22,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50m,
                            IngredientId = 21,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 100m,
                            IngredientId = 18,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 30m,
                            IngredientId = 7,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 6,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 1,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 7,
                            Amount = 150m,
                            IngredientId = 3,
                            MenuItemId = 2,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50m,
                            IngredientId = 17,
                            MenuItemId = 2,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 9,
                            Amount = 40m,
                            IngredientId = 20,
                            MenuItemId = 2,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 2,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 150m,
                            IngredientId = 18,
                            MenuItemId = 3,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 0.15m,
                            IngredientId = 6,
                            MenuItemId = 3,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 13,
                            Amount = 20m,
                            IngredientId = 10,
                            MenuItemId = 3,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 14,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 3,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 15,
                            Amount = 120m,
                            IngredientId = 3,
                            MenuItemId = 4,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 40m,
                            IngredientId = 9,
                            MenuItemId = 4,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 17,
                            Amount = 100m,
                            IngredientId = 21,
                            MenuItemId = 4,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 18,
                            Amount = 0.5m,
                            IngredientId = 25,
                            MenuItemId = 4,
                            UnitType = 0
                        },
                        new
                        {
                            Id = 19,
                            Amount = 80m,
                            IngredientId = 9,
                            MenuItemId = 5,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 20,
                            Amount = 30m,
                            IngredientId = 19,
                            MenuItemId = 5,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 21,
                            Amount = 0.03m,
                            IngredientId = 14,
                            MenuItemId = 5,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 22,
                            Amount = 3m,
                            IngredientId = 13,
                            MenuItemId = 5,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 23,
                            Amount = 150m,
                            IngredientId = 21,
                            MenuItemId = 6,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 24,
                            Amount = 80m,
                            IngredientId = 20,
                            MenuItemId = 6,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 25,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 6,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 26,
                            Amount = 0.2m,
                            IngredientId = 25,
                            MenuItemId = 7,
                            UnitType = 0
                        },
                        new
                        {
                            Id = 27,
                            Amount = 30m,
                            IngredientId = 9,
                            MenuItemId = 7,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 28,
                            Amount = 0.01m,
                            IngredientId = 14,
                            MenuItemId = 7,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 29,
                            Amount = 150m,
                            IngredientId = 1,
                            MenuItemId = 8,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 30,
                            Amount = 30m,
                            IngredientId = 9,
                            MenuItemId = 8,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 31,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 8,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 32,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 8,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 33,
                            Amount = 120m,
                            IngredientId = 9,
                            MenuItemId = 9,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 34,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 9,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 35,
                            Amount = 300m,
                            IngredientId = 1,
                            MenuItemId = 10,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 36,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 10,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 37,
                            Amount = 6m,
                            IngredientId = 13,
                            MenuItemId = 10,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 38,
                            Amount = 250m,
                            IngredientId = 3,
                            MenuItemId = 11,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 39,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 11,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 40,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 11,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 41,
                            Amount = 250m,
                            IngredientId = 2,
                            MenuItemId = 12,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 42,
                            Amount = 10m,
                            IngredientId = 12,
                            MenuItemId = 12,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 43,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 12,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 44,
                            Amount = 200m,
                            IngredientId = 11,
                            MenuItemId = 13,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 45,
                            Amount = 150m,
                            IngredientId = 9,
                            MenuItemId = 13,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 46,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 13,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 47,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 13,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 48,
                            Amount = 200m,
                            IngredientId = 11,
                            MenuItemId = 14,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 49,
                            Amount = 100m,
                            IngredientId = 9,
                            MenuItemId = 14,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 50,
                            Amount = 80m,
                            IngredientId = 2,
                            MenuItemId = 14,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 51,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 14,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 52,
                            Amount = 200m,
                            IngredientId = 11,
                            MenuItemId = 15,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 53,
                            Amount = 250m,
                            IngredientId = 9,
                            MenuItemId = 15,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 54,
                            Amount = 0.02m,
                            IngredientId = 14,
                            MenuItemId = 15,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 55,
                            Amount = 150m,
                            IngredientId = 17,
                            MenuItemId = 16,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 56,
                            Amount = 120m,
                            IngredientId = 5,
                            MenuItemId = 16,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 57,
                            Amount = 30m,
                            IngredientId = 9,
                            MenuItemId = 16,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 58,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 16,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 59,
                            Amount = 150m,
                            IngredientId = 17,
                            MenuItemId = 17,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 60,
                            Amount = 40m,
                            IngredientId = 10,
                            MenuItemId = 17,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 61,
                            Amount = 60m,
                            IngredientId = 9,
                            MenuItemId = 17,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 62,
                            Amount = 3m,
                            IngredientId = 13,
                            MenuItemId = 17,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 63,
                            Amount = 150m,
                            IngredientId = 17,
                            MenuItemId = 18,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 64,
                            Amount = 30m,
                            IngredientId = 10,
                            MenuItemId = 18,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 65,
                            Amount = 30m,
                            IngredientId = 9,
                            MenuItemId = 18,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 66,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 18,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 67,
                            Amount = 120m,
                            IngredientId = 8,
                            MenuItemId = 19,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 68,
                            Amount = 40m,
                            IngredientId = 12,
                            MenuItemId = 19,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 69,
                            Amount = 0.05m,
                            IngredientId = 6,
                            MenuItemId = 19,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 70,
                            Amount = 60m,
                            IngredientId = 11,
                            MenuItemId = 20,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 71,
                            Amount = 50m,
                            IngredientId = 10,
                            MenuItemId = 20,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 72,
                            Amount = 50m,
                            IngredientId = 12,
                            MenuItemId = 20,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 73,
                            Amount = 200m,
                            IngredientId = 8,
                            MenuItemId = 21,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 74,
                            Amount = 50m,
                            IngredientId = 11,
                            MenuItemId = 21,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 75,
                            Amount = 60m,
                            IngredientId = 12,
                            MenuItemId = 21,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 76,
                            Amount = 40m,
                            IngredientId = 10,
                            MenuItemId = 21,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 77,
                            Amount = 0.2m,
                            IngredientId = 6,
                            MenuItemId = 22,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 78,
                            Amount = 10m,
                            IngredientId = 12,
                            MenuItemId = 22,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 79,
                            Amount = 15m,
                            IngredientId = 12,
                            MenuItemId = 23,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 80,
                            Amount = 5m,
                            IngredientId = 12,
                            MenuItemId = 24,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 81,
                            Amount = 250m,
                            IngredientId = 18,
                            MenuItemId = 25,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 82,
                            Amount = 0.1m,
                            IngredientId = 14,
                            MenuItemId = 25,
                            UnitType = 5
                        },
                        new
                        {
                            Id = 83,
                            Amount = 5m,
                            IngredientId = 13,
                            MenuItemId = 25,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 84,
                            Amount = 150m,
                            IngredientId = 15,
                            MenuItemId = 26,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 85,
                            Amount = 50m,
                            IngredientId = 20,
                            MenuItemId = 26,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 86,
                            Amount = 30m,
                            IngredientId = 19,
                            MenuItemId = 26,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 87,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 26,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 88,
                            Amount = 100m,
                            IngredientId = 21,
                            MenuItemId = 27,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 89,
                            Amount = 60m,
                            IngredientId = 20,
                            MenuItemId = 27,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 90,
                            Amount = 60m,
                            IngredientId = 22,
                            MenuItemId = 27,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 91,
                            Amount = 3m,
                            IngredientId = 13,
                            MenuItemId = 27,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 92,
                            Amount = 15m,
                            IngredientId = 12,
                            MenuItemId = 28,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 93,
                            Amount = 3m,
                            IngredientId = 13,
                            MenuItemId = 28,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 94,
                            Amount = 10m,
                            IngredientId = 12,
                            MenuItemId = 29,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 95,
                            Amount = 4m,
                            IngredientId = 13,
                            MenuItemId = 29,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 96,
                            Amount = 80m,
                            IngredientId = 7,
                            MenuItemId = 30,
                            UnitType = 4
                        },
                        new
                        {
                            Id = 97,
                            Amount = 3m,
                            IngredientId = 13,
                            MenuItemId = 30,
                            UnitType = 4
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.Indigriend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Indigriend");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Говядина",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Свинина",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Курица",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Индейка",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Фарш",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Молоко",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сметана",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Творог",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Сыр",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 10,
                            Name = "СливочноеМасло",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Мука",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Сахар",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Соль",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 14,
                            Name = "ПодсолнечноеМасло",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Рис",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Гречка",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 17,
                            Name = "МакаронныеИзделия",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Картофель",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 19,
                            Name = "ЛукРепчатый",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Морковь",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Капуста",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Свекла",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 23,
                            Name = "ХлебПшеничный",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 24,
                            Name = "ХлебРжаной",
                            StockQuantity = 0m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Батон",
                            StockQuantity = 0m
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Available = true,
                            CategoryId = 1,
                            Description = "Классический украинский борщ с мясом, свеклой и сметаной",
                            Name = "Борщ",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Available = true,
                            CategoryId = 1,
                            Description = "Лёгкий куриный бульон с домашней лапшой",
                            Name = "Куриный суп с лапшой",
                            Price = 350m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Available = true,
                            CategoryId = 1,
                            Description = "Нежный суп-пюре из лесных грибов с гренками",
                            Name = "Грибной крем-суп",
                            Price = 420m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Available = true,
                            CategoryId = 2,
                            Description = "Салат с курицей, сыром пармезан и сухариками",
                            Name = "Цезарь с курицей",
                            Price = 480m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Available = true,
                            CategoryId = 2,
                            Description = "Огурцы, помидоры, фета, оливки, красный лук",
                            Name = "Греческий салат",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 6,
                            Available = true,
                            CategoryId = 2,
                            Description = "Микс свежих овощей с оливковым маслом",
                            Name = "Витаминный салат",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 7,
                            Available = true,
                            CategoryId = 3,
                            Description = "Хрустящий хлеб с томатами, базиликом и оливковым маслом",
                            Name = "Брускетта с томатами",
                            Price = 350m
                        },
                        new
                        {
                            MenuItemId = 8,
                            Available = true,
                            CategoryId = 3,
                            Description = "Тонко нарезанная говядина с лимонным соусом",
                            Name = "Карпаччо из говядины",
                            Price = 700m
                        },
                        new
                        {
                            MenuItemId = 9,
                            Available = true,
                            CategoryId = 3,
                            Description = "Сыр моцарелла с томатами и базиликом",
                            Name = "Моцарелла с томатами",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 10,
                            Available = true,
                            CategoryId = 4,
                            Description = "Сочный говяжий стейк, прожарка по желанию",
                            Name = "Стейк рибай",
                            Price = 1500m
                        },
                        new
                        {
                            MenuItemId = 11,
                            Available = true,
                            CategoryId = 4,
                            Description = "Куриное филе на гриле с пряными травами",
                            Name = "Курица гриль",
                            Price = 950m
                        },
                        new
                        {
                            MenuItemId = 12,
                            Available = true,
                            CategoryId = 4,
                            Description = "Мясо свинины с соусом BBQ и овощами",
                            Name = "Свинина в соусе барбекю",
                            Price = 1050m
                        },
                        new
                        {
                            MenuItemId = 13,
                            Available = true,
                            CategoryId = 5,
                            Description = "Томатный соус, сыр моцарелла, базилик",
                            Name = "Маргарита",
                            Price = 650m
                        },
                        new
                        {
                            MenuItemId = 14,
                            Available = true,
                            CategoryId = 5,
                            Description = "Пицца с пепперони и сыром моцарелла",
                            Name = "Пепперони",
                            Price = 750m
                        },
                        new
                        {
                            MenuItemId = 15,
                            Available = true,
                            CategoryId = 5,
                            Description = "Моцарелла, горгонзола, пармезан, чеддер",
                            Name = "Четыре сыра",
                            Price = 850m
                        },
                        new
                        {
                            MenuItemId = 16,
                            Available = true,
                            CategoryId = 6,
                            Description = "Спагетти с мясным соусом и пармезаном",
                            Name = "Спагетти Болоньезе",
                            Price = 700m
                        },
                        new
                        {
                            MenuItemId = 17,
                            Available = true,
                            CategoryId = 6,
                            Description = "Паста с кремовым соусом и сыром",
                            Name = "Феттучини Альфредо",
                            Price = 650m
                        },
                        new
                        {
                            MenuItemId = 18,
                            Available = true,
                            CategoryId = 6,
                            Description = "Паста с креветками, кальмарами и чесночным соусом",
                            Name = "Паста с морепродуктами",
                            Price = 950m
                        },
                        new
                        {
                            MenuItemId = 19,
                            Available = true,
                            CategoryId = 7,
                            Description = "Классический итальянский десерт с маскарпоне и кофе",
                            Name = "Тирамису",
                            Price = 400m
                        },
                        new
                        {
                            MenuItemId = 20,
                            Available = true,
                            CategoryId = 7,
                            Description = "Тёплый шоколадный кекс с жидкой начинкой",
                            Name = "Шоколадный фондан",
                            Price = 420m
                        },
                        new
                        {
                            MenuItemId = 21,
                            Available = true,
                            CategoryId = 7,
                            Description = "Классический чизкейк с клубничным соусом",
                            Name = "Чизкейк Нью-Йорк",
                            Price = 450m
                        },
                        new
                        {
                            MenuItemId = 22,
                            Available = true,
                            CategoryId = 8,
                            Description = "Эспрессо с горячим молоком и пенкой",
                            Name = "Капучино",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 23,
                            Available = true,
                            CategoryId = 8,
                            Description = "Классический черный чай",
                            Name = "Чай черный",
                            Price = 150m
                        },
                        new
                        {
                            MenuItemId = 24,
                            Available = true,
                            CategoryId = 8,
                            Description = "Свежевжатый апельсиновый сок",
                            Name = "Сок апельсиновый",
                            Price = 200m
                        },
                        new
                        {
                            MenuItemId = 25,
                            Available = true,
                            CategoryId = 9,
                            Description = "Хрустящий картофель фри",
                            Name = "Картофель фри",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 26,
                            Available = true,
                            CategoryId = 9,
                            Description = "Отварной рис с овощами",
                            Name = "Рис с овощами",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 27,
                            Available = true,
                            CategoryId = 9,
                            Description = "Сезонные овощи на пару",
                            Name = "Овощи на пару",
                            Price = 230m
                        },
                        new
                        {
                            MenuItemId = 28,
                            Available = true,
                            CategoryId = 10,
                            Description = "Сладко-пряный соус для мяса",
                            Name = "Соус BBQ",
                            Price = 100m
                        },
                        new
                        {
                            MenuItemId = 29,
                            Available = true,
                            CategoryId = 10,
                            Description = "Соус из томатов для пиццы и пасты",
                            Name = "Томатный соус",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 30,
                            Available = true,
                            CategoryId = 10,
                            Description = "Нежный соус со сметаной и зеленью",
                            Name = "Сметанный соус",
                            Price = 80m
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CafeAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Waiter"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Cook"
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Admin",
                            Login = "admin",
                            PasswordHash = "$2a$12$.gijsKvNhylDhZfxAknuDesvmZnx13DhA2NVKk9LZH32YiRAQM8YW",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Waiter",
                            Login = "waiter",
                            PasswordHash = "$2a$12$C2Ek4ejvfw.so/k2AezYpuflw5YAaQ4vmHqU0xq0Gmz85Z.I3bSyG",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Cook",
                            Login = "cook",
                            PasswordHash = "$2a$12$9iwlfcfL1S1uYa7BLe3xZO03pZ7mOTQzZDDGWOP7h/Xq4GaCSNBCm",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("CafeAPI.Models.DishItems", b =>
                {
                    b.HasOne("CafeAPI.Models.Indigriend", "Ingredient")
                        .WithMany("DishItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeAPI.Models.MenuItem", "MenuItem")
                        .WithMany("DishItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.HasOne("CafeAPI.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.HasOne("CafeAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeAPI.Models.OrderItem", b =>
                {
                    b.HasOne("CafeAPI.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.HasOne("CafeAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafeAPI.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Indigriend", b =>
                {
                    b.Navigation("DishItems");
                });

            modelBuilder.Entity("CafeAPI.Models.MenuItem", b =>
                {
                    b.Navigation("DishItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CafeAPI.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
